-- ============================================================================
-- Table: users
-- Description:
--   Stores core YourApp user identity records.
--   Uses Rust-generated UUIDv7 for clustered B-Tree indexing performance.
-- ============================================================================
CREATE TABLE IF NOT EXISTS users (
    -- Primary key: UUIDv7 generated by the application layer.
    id UUID PRIMARY KEY,

    -- Timestamp indicating when the user record was created (UTC).
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- Table: oauth_links
-- Description:
--   Links third-party OAuth providers (Google, Apple, Facebook) to a YourApp user.
-- ============================================================================
CREATE TABLE IF NOT EXISTS oauth_links (
    -- Foreign key referencing the primary identity record in the users table.
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Name of the third-party OAuth provider (e.g., 'google', 'apple').
    provider TEXT NOT NULL,

    -- Unique subject identifier provided by the OAuth provider ('sub' claim).
    provider_subject_id TEXT NOT NULL,

    -- Timestamp indicating when the OAuth link was created (UTC).
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Composite primary key ensuring provider account uniqueness.
    PRIMARY KEY (provider, provider_subject_id)
);

-- ============================================================================
-- Index: idx_oauth_links_user_id
-- Description:
--   Optimizes reverse lookups to find all OAuth links belonging to a user.
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_oauth_links_user_id ON oauth_links(user_id);

-- ============================================================================
-- Table: local_credentials
-- Description:
--   Stores traditional email and Argon2id password hashes for manual accounts.
--   Treated as a "local provider" link to the core user record.
-- ============================================================================
CREATE TABLE IF NOT EXISTS local_credentials (
    -- Foreign key referencing the primary identity record in the users table.
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,

    -- User's email address used for login and authentication.
    email TEXT NOT NULL UNIQUE,

    -- Stored output of the Argon2id key derivation function.
    password_hash TEXT NOT NULL,

    -- Timestamp indicating when local credentials were created (UTC).
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- Index: idx_local_credentials_email
-- Description:
--   Optimizes email lookups during local password authentication/login.
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_local_credentials_email ON local_credentials(email);
