//! # Google reCAPTCHA Verification Engine
//!
//! This module provides the integration for verifying user tokens against the
//! Google reCAPTCHA API endpoint (`https://www.google.com/recaptcha/api/siteverify`).
//!
//! It implements the [`VerificationProvider`] trait to allow pluggable human-verification
//! strategies across your authentication and security microservices.

use super::VerificationProvider;
use async_trait::async_trait;
use reqwest::Client;
use serde::Deserialize;

/// Internal structure representing the JSON response payload returned by the
/// Google reCAPTCHA verification web service.
#[derive(Deserialize)]
struct RecaptchaResponse {
    /// Indicates whether the user response was verified successfully by Google.
    success: bool,
}

/// A verification provider that validates tokens using Google reCAPTCHA v2 or v3.
///
/// Encapsulates an HTTP client pool and the server-side secret key required
/// to authenticate verification requests against Google's API.
pub struct RecaptchaProvider {
    secret_key: String,
    http_client: Client,
}

impl RecaptchaProvider {
    /// Creates a new instance of the `RecaptchaProvider`.
    ///
    /// # Arguments
    ///
    /// * `secret_key` - Your Google reCAPTCHA secret key issued by the Google Cloud console.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use crate::verification::RecaptchaProvider; // Adjust path as appropriate
    ///
    /// let provider = RecaptchaProvider::new("your-secret-key-here".to_string());
    /// ```
    pub fn new(secret_key: String) -> Self {
        Self {
            secret_key,
            http_client: Client::new(),
        }
    }
}

#[async_trait]
impl VerificationProvider for RecaptchaProvider {
    /// Verifies a client-side reCAPTCHA response token against Google's API.
    ///
    /// Sends an HTTP `POST` request with form-urlencoded data containing the secret key
    /// and the provided user token.
    ///
    /// # Arguments
    ///
    /// * `token` - The challenge response string generated by the frontend reCAPTCHA widget.
    ///
    /// # Returns
    ///
    /// * `Ok(true)` if Google confirms the token is valid and verified.
    /// * `Ok(false)` if the token is invalid, expired, or failed verification.
    /// * `Err(...)` if a network failure occurs, the HTTP request fails, or JSON deserialization fails.
    async fn verify(&self, token: &str) -> Result<bool, Box<dyn std::error::Error + Send + Sync>> {
        let url = "https://www.google.com/recaptcha/api/siteverify";
        let body = format!("secret={}&response={}", self.secret_key, token);

        let response: RecaptchaResponse = self
            .http_client
            .post(url)
            .header("Content-Type", "application/x-www-form-urlencoded")
            .body(body)
            .send()
            .await?
            .json()
            .await?;

        Ok(response.success)
    }
}
