//! # Cloudflare Turnstile Verification Engine
//!
//! This module provides the integration for verifying user tokens against the
//! Cloudflare Turnstile API endpoint (`https://challenges.cloudflare.com/turnstile/v0/siteverify`).
//!
//! It implements the [`VerificationProvider`] trait to allow pluggable human-verification
//! strategies across your authentication and security microservices.

use super::VerificationProvider;
use async_trait::async_trait;
use reqwest::Client;
use serde::Deserialize;

/// Internal structure representing the JSON response payload returned by the
/// Cloudflare Turnstile verification web service.
#[derive(Deserialize)]
struct TurnstileResponse {
    /// Indicates whether the user response was verified successfully by Cloudflare.
    success: bool,
}

/// A verification provider that validates tokens using Cloudflare Turnstile.
///
/// Encapsulates an HTTP client pool and the server-side secret key required
/// to authenticate verification requests against Cloudflare's API.
pub struct TurnstileProvider {
    secret_key: String,
    http_client: Client,
}

impl TurnstileProvider {
    /// Creates a new instance of the `TurnstileProvider`.
    ///
    /// # Arguments
    ///
    /// * `secret_key` - Your Cloudflare Turnstile secret key issued by the Cloudflare dashboard.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use crate::verification::TurnstileProvider; // Adjust path as appropriate
    ///
    /// let provider = TurnstileProvider::new("your-turnstile-secret-key-here".to_string());
    /// ```
    pub fn new(secret_key: String) -> Self {
        Self {
            secret_key,
            http_client: Client::new(),
        }
    }
}

#[async_trait]
impl VerificationProvider for TurnstileProvider {
    /// Verifies a client-side Turnstile response token against Cloudflare's API.
    ///
    /// Sends an HTTP `POST` request with form-urlencoded data containing the secret key
    /// and the provided user token.
    ///
    /// # Arguments
    ///
    /// * `token` - The challenge response string generated by the frontend Turnstile widget.
    ///
    /// # Returns
    ///
    /// * `Ok(true)` if Cloudflare confirms the token is valid and verified.
    /// * `Ok(false)` if the token is invalid, expired, or failed verification.
    /// * `Err(...)` if a network failure occurs, the HTTP request fails, or JSON deserialization fails.
    async fn verify(&self, token: &str) -> Result<bool, Box<dyn std::error::Error + Send + Sync>> {
        let url = "https://challenges.cloudflare.com/turnstile/v0/siteverify";
        let body = format!("secret={}&response={}", self.secret_key, token);

        let response: TurnstileResponse = self
            .http_client
            .post(url)
            .header("Content-Type", "application/x-www-form-urlencoded")
            .body(body)
            .send()
            .await?
            .json()
            .await?;

        Ok(response.success)
    }
}
