[package]
name = "your_app_identity"
version = "0.1.0"
edition = "2021"

[dependencies]
time = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
argon2 = "0.5"
jsonwebtoken = { workspace = true }
reqwest = { workspace = true }

your_app_contracts = { path = "../contracts" }
