[package]
name = "your_app_access_tokens"
version = "0.1.0"
edition = "2021"

[features]
default = []
local-dev = []

[dependencies]
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-opentelemetry = { workspace = true }
serde = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
jsonwebtoken = { workspace = true }
rsa = { workspace = true }
pkcs8 = { workspace = true }
base64 = { workspace = true }
sha2 = { workspace = true }
rand = { workspace = true }

your_app_telemetry = { path = "../telemetry" }
your_app_contracts = { path = "../contracts" }
