name: YourApp CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-and-contracts:
    name: Contracts & React Portal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.0.0'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '9.15.4'
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('website/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Generate TypeScript Contracts
        run: just check-contracts

      - name: Build React Frontend
        run: just check-frontend

  rust-backend:
    name: Rust Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.97.0
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run Rust pipeline
        env:
          SQLX_OFFLINE: true
        run: just check-rust
